server:
  port: 8051
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#eureka.client.service-url.defaultZone=http://localhost:8051/eureka/
## 消息模板配置
message:
  global:
    '4001000': '{}'
    '4001001': '未登录'
    '4001002': '未登录令牌已失效,请尝试重新登录'
    '4001003': '您无权限访问'
    '4001004': '{}不存在'
    '4001005': '获取用户信息失败'
    '4001006': '{}已经存在'
    '4001007': '{}已被使用'
    '4001008': '非法参数'
    '4001009': '{}不能为空'
    '4001010': '{}操作失败'
    '4001011': '请求超时'
    '4001012': '服务异常'
    '4001013': '验证码过期'
    '4001014': '验证码无效'
    '4001016': '签名验证失败'
    '4001017': '开户失败：{}'
    '4001018': '用户未审核或审核未通过'
    '4001019': '{}被禁用'
    '4001020': '{}不正确'
    '4001021': '请勿频繁请求'
    '4001022': '您的帐号在其它地方登录，您已被迫下线 ！'
